version: '3.9'

services:
  nm-mgr:
    container_name: nm-mgr
    hostname: nm-mgr
    build:
      context: ..
      dockerfile: testenv/Dockerfile
    ports:
      - "1113:1113/udp"
      - "4556:4556/udp"
      - "8089:8089/tcp"
    depends_on: {}
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      container: docker
      ION_NODE_NUM: 1
      MGR_NODE_NUM: 1
