sonar.projectKey=JHUAPL-DTNMA_dtnma-tools
sonar.organization=jhuapl-dtnma

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Reference Tools
sonar.projectVersion=2.2.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=test,item-test
# ignore old/test sources
sonar.exclusions=oldsrc/**/*,**/*.cbor

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
