volumes:
  postgres-data:
    # temporary storage
  sockdir:
    # shared sockets

networks:
  default:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  postgres:
    build:
      context: ../refdb-sql
      dockerfile: Containerfile
    hostname: postgres
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  amp-manager:
    hostname: amp-manager
    build:
      context: ..
      dockerfile: integration-test-proxy/Containerfile
      target: amp-manager
    ports:
      - "8089:8089/tcp"
    depends_on:
      postgres:
        condition: service_healthy
      ion-manager:
        condition: service_started
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - "sockdir:${SOCKDIR}"
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      AMP_PROXY_SOCKET: "${SOCKDIR}/proxy.sock"
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  ion-manager:
    hostname: ion-manager
    build:
      context: ..
      dockerfile: integration-test-proxy/Containerfile
      target: ion-manager
    depends_on: {}
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - "/var/tmp/pcap:/var/log/pcap"
      - "sockdir:${SOCKDIR}"
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      AMP_PROXY_SOCKET: "${SOCKDIR}/proxy.sock"
      ION_NODE_NUM: 1
      MGR_NODE_NUM: 1
      DUMPCAP_OUTFILE: /var/log/pcap/manager.pcap
      DUMPCAP_OPTS: -i lo -i eth0
    networks:
      default:
        ipv4_address: 10.5.0.101

  agent1:
    hostname: agent1
    build:
      context: ..
      dockerfile: integration-test-proxy/Containerfile
      target: agent
    depends_on:
      ion-manager:
        condition: service_started
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - "/var/tmp/pcap:/var/log/pcap"
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      ION_NODE_NUM: 2
      MGR_NODE_NUM: 1
      DUMPCAP_OUTFILE: /var/log/pcap/agent1.pcap
      DUMPCAP_OPTS: -i lo -i eth0
    networks:
      default:
        ipv4_address: 10.5.0.102
