##
## Copyright (c) 2011-2024 The Johns Hopkins University Applied Physics
## Laboratory LLC.
##
## This file is part of the Delay-Tolerant Networking Management
## Architecture (DTNMA) Tools package.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##     http://www.apache.org/licenses/LICENSE-2.0
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
FROM docker.io/library/ubuntu:24.04 AS os-base
ENV DEBIAN_FRONTEND="noninteractive"

# APL network configuration from
# https://aplprod.servicenowservices.com/sp?id=kb_article&sys_id=c0de6fe91b83d85071b143bae54bcb34
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y ca-certificates curl && \
    (curl -sL http://apllinuxdepot.jhuapl.edu/linux/APL-root-cert/JHUAPL-MS-Root-CA-05-21-2038-B64-text.cer -o /usr/local/share/ca-certificates/JHUAPL-MS-Root-CA-05-21-2038-B64-text.crt || true) && \
    update-ca-certificates
ENV PIP_CERT=/etc/ssl/certs/ca-certificates.crt
ENV PIP_DEFAULT_TIMEOUT=300
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Distro upgrade for security patches
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get upgrade -y && \
    rm -f /var/lib/man-db/auto-update

# Testing utilities
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    net-tools iproute2 iputils-ping \
    lsof iftop gdb valgrind xxd socat jq ruby && \
    gem install cbor-diag


FROM os-base AS systemd-base

# Use systemd as top-level process
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y systemd systemd-sysv
RUN systemctl mask systemd-logind && \
    systemctl mask console-getty && \
    systemctl disable getty@tty1 && \
    systemctl disable apt-daily.timer apt-daily-upgrade.timer && \
    systemctl disable systemd-timesyncd && \
    systemctl disable systemd-networkd && \
    echo "MulticastDNS=no" >>/etc/systemd/resolved.conf
CMD [ "/sbin/init" ]

COPY --chmod=755 systemd/service_is_running.sh /usr/local/bin/service_is_running


FROM ubuntu:24.04 AS build-local

RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    build-essential \
    cmake autoconf libtool && \
    echo "/usr/local/lib" >/etc/ld.so.conf.d/local.conf

COPY deps/ion /usr/local/src/nm/deps/ion
COPY deps/ion*.patch /usr/local/src/nm/deps/
RUN cd /usr/local/src/nm/deps/ion && \
    patch -p1 <../ion-4.1.4-remove-nm.patch && \
    autoreconf -vif && \
    export CFLAGS="-std=gnu99 -Wno-error=pedantic" && \
    ./configure && \
    make -j$(nproc) && \
    export LIBTOOLFLAGS="-Wnone" && \
    make install && \
    make -j$(nproc) clean

COPY deps/QCBOR /usr/local/src/nm/deps/QCBOR
RUN cd /usr/local/src/nm/deps/QCBOR && \
    cmake -S . -B build \
      -DCMAKE_BUILD_TYPE=Debug \
      -DBUILD_SHARED_LIBS=YES && \
    cmake --build build && \
    cmake --install build && \
    ldconfig && \
    rm -rf build

COPY deps/mlib /usr/local/src/nm/deps/mlib
RUN cd /usr/local/src/nm/deps/mlib && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    make -j$(nproc) clean

COPY deps/timespec /usr/local/src/nm/deps/timespec
COPY deps/timespec-CMakeLists.txt /usr/local/src/nm/deps/timespec/CMakeLists.txt
RUN cd /usr/local/src/nm/deps/timespec && \
    cmake -S . -B build \
      -DCMAKE_BUILD_TYPE=Debug && \
    cmake --build build && \
    cmake --install build && \
    ldconfig && \
    rm -rf build

# REFDA and REFDM to test
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    cmake ninja-build ruby pkg-config \
    flex libfl-dev bison libpcre2-dev libpq-dev civetweb libcivetweb-dev libcjson-dev libsystemd-dev
COPY cmake /usr/local/src/nm/cmake
COPY src /usr/local/src/nm/src
COPY CMakeLists.txt /usr/local/src/nm/
RUN cd /usr/local/src/nm && \
    cmake -S . -B build/default \
      -DCMAKE_BUILD_TYPE=Debug \
      -DBUILD_ION_PROXY=ON \
      -DTRANSPORT_UNIX_SOCKET=OFF \
      -DTRANSPORT_PROXY_SOCKET=ON \
      -DTRANSPORT_ION_BP=ON \
      -DBUILD_UNITTEST=OFF -DBUILD_FUZZING=OFF \
      -DBUILD_DOCS_API=OFF -DBUILD_DOCS_MAN=OFF \
      -G Ninja && \
    cmake --build build/default && \
    cmake --install build/default && \
    ldconfig && \
    rm -rf build


FROM os-base AS client

# Helper utilities
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    curl git \
    python3 python3-pip python3-wheel
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install schemathesis
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install git+https://github.com/JHUAPL-DTNMA/dtnma-ace.git@main
RUN git clone --branch main https://github.com/JHUAPL-DTNMA/dtnma-adms.git /usr/local/share/ace/adms

# test config
COPY integration-test-socket/schemathesis.toml integration-test-socket/serializers.py /root/

WORKDIR "/root"
CMD ["sh", "-c", "trap \"exit\" TERM; while true; do sleep 1; done"]


FROM os-base AS amp-manager

# Test tools
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    curl postgresql-client

# REFDM
RUN --mount=type=cache,target=/var/lib/apt/lists \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && apt-get install -y \
    libcivetweb1 libcjson1
COPY --from=build-local /usr/local /usr/local
RUN ldconfig
CMD ["sh", "-c", "refdm-proxy -l ${DTNMA_LOGLEVEL} -a ${AMP_PROXY_SOCKET} -t 30"]

EXPOSE 8089/tcp


FROM systemd-base AS ion-manager

# ION files
COPY --from=build-local /usr/local /usr/local
RUN ldconfig

# Systemd services
COPY integration-test-ion/tmpfiles.conf /etc/tmpfiles.d/ion.conf
COPY --chmod=644 systemd/ion.service systemd/ion-app-proxy.service systemd/bpecho@.service \
    /usr/local/lib/systemd/system/
RUN systemctl enable ion bpecho@4 ion-app-proxy && \
    mkdir -p /var/run/ion

# Runtime config for this container
COPY integration-test-ion/node-*.rc /etc/ion/

HEALTHCHECK --start-period=10s --interval=10s --timeout=5s --retries=5 \
    CMD ["service_is_running", "ion", "ion-app-proxy"]
EXPOSE 4556/udp


FROM systemd-base AS ion-agent

# ION files
COPY --from=build-local /usr/local /usr/local
RUN ldconfig

# Systemd services
COPY integration-test-ion/tmpfiles.conf /etc/tmpfiles.d/ion.conf
COPY --chmod=644 systemd/ion.service systemd/bpecho@.service systemd/dumpcap.service \
    /usr/local/lib/systemd/system/
RUN systemctl enable ion bpecho@4 dumpcap && \
    mkdir -p /var/run/ion

# Runtime config for this container
COPY integration-test-ion/node-*.rc /etc/ion/

HEALTHCHECK --start-period=10s --interval=10s --timeout=5s --retries=5 \
    CMD ["service_is_running", "ion"]
EXPOSE 4556/udp


FROM os-base AS amp-agent

# REFDA
COPY --from=build-local /usr/local /usr/local
RUN ldconfig
CMD ["sh", "-c", "refda-ion -l ${DTNMA_LOGLEVEL} -s /etc/refda/startup.uri -a ipn:${ION_NODE_NUM}.6 -m ipn:${MGR_NODE_NUM}.7"]

# Runtime config for this container
COPY integration-test-ion/startup.uri /etc/refda/startup.uri
