# module file in same directory as this config
hooks = "serializers.py"

[phases.coverage]
# Only test these as unsupported method
#unexpected-methods = ["OPTIONS", "PUT", "POST", "DELETE", "PATCH"]
# work around 404 vs 405 bug
unexpected-methods = []

[phases.fuzzing]
enabled = false

[phases.stateful]
max-steps = 5

[generation]
codec = "ascii"
max-examples = 20

[checks]
positive_data_acceptance.expected-statuses = [
    "200", "201", "202", "204",
    "400", # ARI content is just bad
    "404", # no such EID
    "415", "422", # mismatch between query and content-type
    "504" # failure to send
]
negative_data_rejection.expected-statuses = [
    "400", "401", "403", "404", "405", "406", "409", "415", "422", "428"
]
not_a_server_error.expected-statuses = [
    "2xx", "3xx", "4xx",
    "504" # failure to send
]
