volumes:
  postgres-data:
    # temporary storage

services:
  postgres:
    build:
      context: ../refdb-sql
      dockerfile: Containerfile
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  manager:
    hostname: manager
    build:
      context: ..
      dockerfile: integration-test-ion/Containerfile
      target: manager
    ports:
      - "8089:8089/tcp"
    depends_on:
      postgres:
        condition: service_healthy
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - /var/tmp/pcap:/var/log/pcap
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      ION_NODE_NUM: 1
      MGR_NODE_NUM: 1
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DUMPCAP_OUTFILE: /var/log/pcap/manager.pcap
      DUMPCAP_OPTS: -i lo -i eth0

  agent1:
    hostname: agent1
    build:
      context: ..
      dockerfile: integration-test-ion/Containerfile
      target: agent
    depends_on:
      manager:
        condition: service_started
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - /var/tmp/pcap:/var/log/pcap
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      ION_NODE_NUM: 2
      MGR_NODE_NUM: 1
      DUMPCAP_OUTFILE: /var/log/pcap/agent1.pcap
      DUMPCAP_OPTS: -i lo -i eth0
