services:
  manager:
    hostname: manager
    build:
      context: ..
      dockerfile: integration-test-ion/Containerfile
      target: manager
    ports:
      - "8089:8089/tcp"
    depends_on: {}
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - /var/tmp/pcap:/var/log/pcap
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      ION_NODE_NUM: 1
      MGR_NODE_NUM: 1
      DUMPCAP_OUTFILE: /var/log/pcap/manager.pcap
      DUMPCAP_OPTS: -i lo -i eth0

  agent1:
    hostname: agent1
    build:
      context: ..
      dockerfile: integration-test-ion/Containerfile
      target: agent
    depends_on:
      manager:
        condition: service_started
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - /var/tmp/pcap:/var/log/pcap
    environment:
      container: docker
      DTNMA_LOGLEVEL: debug
      ION_NODE_NUM: 2
      MGR_NODE_NUM: 1
      DUMPCAP_OUTFILE: /var/log/pcap/agent1.pcap
      DUMPCAP_OPTS: -i lo -i eth0
