version: '3.9'

services:
  postgres:
    container_name: ${DOCKER_CTR_PREFIX}postgres
    hostname: postgres
    image: ${DOCKER_IMAGE_PREFIX}amp-sql:${DOCKER_IMAGE_TAG}
    restart: unless-stopped
    security_opt:
      - "label=type:postgres.process"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT-5432}:5432"

  nm-mgr:
    container_name: nm-mgr
    hostname: nm-mgr
    build:
      context: ..
      dockerfile: testenv/Dockerfile
    ports:
      - "1113:1113/udp"
      - "4556:4556/udp"
      - "8089:8089/tcp"
    depends_on: 
      postgres:
        condition: service_healthy
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      container: docker
      ION_NODE_NUM: 1
      MGR_NODE_NUM: 1
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
