name: Source formatting

on:
  push:
    branches: [ "main" ]
  pull_request: {} # any target
  schedule:
    - cron: '20 8 * * 4'

jobs:
  check-formatting:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up OS
        run: >
          sudo apt-get update && sudo apt-get install -y
          clang-format
      - name: Check code formatting
        run: ./check_format.sh
